import type { CurrentUser } from '@erp/contracts';

export const demoUser: CurrentUser = {
  id: '018f4f12-2222-7222-8222-000000000001',
  email: 'gestor@demo.local',
  displayName: 'Marina Costa',
  companyId: '018f4f12-2222-7222-8222-000000000002',
  branchId: '018f4f12-2222-7222-8222-000000000003',
  modules: [
    'core',
    'catalog',
    'sales',
    'stock',
    'purchases',
    'integrations',
    'production',
    'finance',
    'food',
    'fiscal',
    'logistics',
  ],
  permissions: [
    'catalog.products.read',
    'catalog.products.manage',
    'catalog.price.manage',
    'catalog.cost.read',
    'sales.quotes.read',
    'sales.orders.read',
    'sales.quotes.manage',
    'sales.orders.manage',
    'sales.discounts.apply',
    'sales.pos.use',
    'sales.pos.discount',
    'sales.pos.settings.manage',
    'sales.credit.read',
    'sales.credit.receive',
    'finance.cash.read',
    'finance.cash.operate',
    'finance.cash.reopen',
    'food.tables.read',
    'food.tables.manage',
    'food.tabs.operate',
    'fiscal.nfce.issue',
    'fiscal.nfe.issue',
    'fiscal.settings.manage',
    'sales.receipts.print',
    'logistics.deliveries.read',
    'logistics.deliveries.operate',
    'logistics.settings.manage',
    'stock.inventory.read',
    'stock.adjustments.create',
    'stock.movements.read',
    'purchases.suggestions.read',
    'purchases.suggestions.calculate',
    'purchases.quotations.read',
    'purchases.quotations.manage',
    'purchases.xml.read',
    'purchases.xml.import',
    'integrations.whatsapp.read',
    'integrations.whatsapp.manage',
    'integrations.whatsapp.send',
    'production.orders.read',
    'production.engineering.read',
    'production.engineering.manage',
    'production.orders.manage',
    'production.orders.finalize',
    'master.customers.read',
    'master.customers.manage',
    'master.suppliers.read',
    'master.suppliers.manage',
    'master.employees.read',
    'master.employees.manage',
    'admin.subscription.read',
    'admin.branches.read',
    'admin.users.read',
    'admin.roles.read',
  ],
};

export function demoResponse(path: string, method = 'GET'): unknown {
  if (path.startsWith('/catalog/products'))
    return {
      items: [
        {
          id: 'p1',
          code: 'CAF-001',
          barcode: '7891000100103',
          description: 'Café Especial 500 g',
          unitCode: 'UN',
          shortDescription: 'Café 500 g',
          unitId: 'u1',
          active: true,
          controlsLot: true,
          controlsExpiry: true,
          price: { salePrice: '32.90', minimumPrice: '29.90', cost: '21.40' },
        },
        {
          id: 'p2',
          code: 'LEI-001',
          barcode: '7891000200209',
          description: 'Leite Integral 1 L',
          unitCode: 'UN',
          shortDescription: 'Leite 1 L',
          unitId: 'u1',
          active: true,
          controlsLot: true,
          controlsExpiry: true,
          price: { salePrice: '6.49', minimumPrice: '5.90', cost: '4.12' },
        },
        {
          id: 'p3',
          code: 'PAO-001',
          barcode: '7891000300305',
          description: 'Pão de Queijo Artesanal',
          shortDescription: 'Pão de queijo',
          unitId: 'u1',
          active: true,
          controlsLot: false,
          controlsExpiry: false,
          price: { salePrice: '12.50', minimumPrice: '10.00', cost: '6.80' },
        },
      ],
      total: 3,
      page: 1,
      pageSize: 20,
    };
  if (path === '/catalog/lookups')
    return {
      groups: [],
      categories: [],
      brands: [],
      units: [{ id: 'u1', code: 'UN', name: 'Unidade' }],
      priceTables: [{ id: 't1', code: 'PADRAO', name: 'Padrão' }],
      branches: [{ id: demoUser.branchId, code: 'MATRIZ', name: 'Loja Centro' }],
    };
  if (path === '/sales/pos/lookups')
    return {
      issuer: {
        tradeName: 'ERP Híbrido Mercado',
        legalName: 'ERP Híbrido Comércio e Tecnologia Ltda.',
        taxId: '01027058000191',
      },
      settings: {
        defaultCustomerId: null,
        defaultSellerId: '018f4f12-2222-7222-8222-000000000201',
        defaultLocationId: '018f4f12-2222-7222-8222-000000000401',
        sellerMode: 'per_sale',
      },
      customers: [
        { id: '018f4f12-2222-7222-8222-000000000101', name: 'Ana Martins' },
        { id: '018f4f12-2222-7222-8222-000000000102', name: 'Mercado Boa Mesa' },
      ],
      sellers: [{ id: '018f4f12-2222-7222-8222-000000000201', name: 'Marina Costa' }],
      paymentMethods: [
        {
          id: '018f4f12-2222-7222-8222-000000000301',
          code: 'DINHEIRO',
          name: 'Dinheiro',
          type: 'cash',
        },
        { id: '018f4f12-2222-7222-8222-000000000302', code: 'PIX', name: 'PIX', type: 'pix' },
        {
          id: '018f4f12-2222-7222-8222-000000000303',
          code: 'CREDIARIO',
          name: 'Crediário',
          type: 'credit_account',
        },
        {
          id: '018f4f12-2222-7222-8222-000000000304',
          code: 'CREDITO',
          name: 'Cartão de crédito',
          type: 'credit_card',
          maxInstallments: 12,
          cardConfiguration: {
            operatorName: 'Rede',
            debitRate: '1.49',
            creditRate: '2.89',
            installmentRate: '0.35',
            settlementDays: 30,
          },
        },
      ],
      locations: [
        { id: '018f4f12-2222-7222-8222-000000000401', code: 'LOJA', name: 'Estoque da loja' },
      ],
      products: [
        {
          id: 'p1',
          code: 'CAF-001',
          barcode: '7891000100103',
          description: 'Café Especial 500 g',
          openPrice: false,
          controlsLot: true,
          controlsExpiry: true,
          selectLotAtPos: true,
          salePrice: '32.90',
          availableQuantity: '18',
          lots: [
            {
              id: '018f4f12-2222-7222-8222-000000000811',
              lotNumber: 'CAF-0826-A',
              expiresAt: '2026-09-12T00:00:00.000Z',
              availableQuantity: '7',
            },
            {
              id: '018f4f12-2222-7222-8222-000000000812',
              lotNumber: 'CAF-1026-B',
              expiresAt: '2026-10-30T00:00:00.000Z',
              availableQuantity: '11',
            },
            {
              id: '018f4f12-2222-7222-8222-000000000813',
              lotNumber: 'CAF-VENCIDO',
              expiresAt: '2026-07-10T00:00:00.000Z',
              availableQuantity: '2',
            },
          ],
        },
        {
          id: 'p2',
          code: 'LEI-001',
          barcode: '7891000200209',
          description: 'Leite Integral 1 L',
          openPrice: false,
          controlsLot: true,
          controlsExpiry: true,
          selectLotAtPos: false,
          salePrice: '6.49',
          availableQuantity: '42',
          lots: [],
        },
        {
          id: 'p3',
          code: 'PAO-001',
          barcode: '7891000300305',
          description: 'Pão de Queijo Artesanal',
          openPrice: false,
          controlsLot: false,
          controlsExpiry: false,
          selectLotAtPos: false,
          salePrice: '12.50',
          availableQuantity: '25',
          lots: [],
        },
      ],
    };
  if (path === '/sales/pos/settings')
    return {
      defaultCustomerId: null,
      defaultSellerId: '018f4f12-2222-7222-8222-000000000201',
      defaultLocationId: '018f4f12-2222-7222-8222-000000000401',
      sellerMode: 'per_sale',
    };
  if (path === '/sales/lookups')
    return {
      customers: [
        { id: 'customer-1', name: 'Ana Martins' },
        { id: 'customer-2', name: 'Mercado Boa Mesa' },
      ],
      sellers: [
        { id: 'seller-1', name: 'Marina Costa' },
        { id: 'seller-2', name: 'Carlos Lima' },
      ],
      paymentMethods: [
        { id: 'method-1', name: 'PIX' },
        { id: 'method-2', name: 'Boleto' },
      ],
      products: [
        {
          id: 'product-1',
          code: 'CAF-001',
          description: 'Café Especial 500 g',
          controlsLot: true,
          controlsExpiry: true,
          openPrice: false,
          price: { salePrice: '32.90' },
        },
        {
          id: 'product-2',
          code: 'LEI-001',
          description: 'Leite Integral 1 L',
          controlsLot: true,
          controlsExpiry: true,
          openPrice: false,
          price: { salePrice: '6.49' },
        },
      ],
      locations: [{ id: 'location-1', code: 'EXP', name: 'Expedição' }],
      lots: [],
    };
  if (path === '/sales/quotes') return { items: [], total: 0, page: 1, pageSize: 20 };
  if (path === '/sales/orders' && method !== 'GET')
    return demoOrder('order-new', 'PED-000429', 'separation', 'Ana Martins', '164.50');
  if (path === '/sales/orders')
    return {
      items: [
        demoOrder('order-1', 'PED-000428', 'separation', 'Ana Martins', '219.80'),
        demoOrder('order-2', 'PED-000427', 'invoicing', 'Mercado Boa Mesa', '648.40'),
        demoOrder('order-3', 'PED-000426', 'delivery', 'Carlos Nobre', '98.70'),
        demoOrder('order-4', 'PED-000425', 'completed', 'Beatriz Lima', '312.60'),
      ],
      total: 4,
      page: 1,
      pageSize: 20,
    };
  if (path.startsWith('/sales/orders/'))
    return demoOrder(
      path.split('/')[3] ?? 'order-1',
      'PED-000428',
      'separation',
      'Ana Martins',
      '219.80',
    );
  if (path === '/cash/dashboard') {
    const daily = [
      980, 1240, 890, 1630, 1450, 1890, 2100, 1760, 2380, 2040, 2670, 2310, 2940, 3184,
    ];
    const monthly = [
      18200, 21400, 19800, 24600, 27100, 25800, 30400, 32900, 35100, 38700, 41200, 44850,
    ];
    return {
      updatedAt: new Date().toISOString(),
      metrics: {
        todayGross: '3184.70',
        todaySales: 37,
        monthGross: '44850.30',
        monthSales: 426,
        averageTicket: '105.28',
        pendingOrders: 8,
        openReceivables: '12740.80',
        lowStockProducts: 14,
      },
      daily: daily.map((value, index) => ({
        label: `${String(index + 16).padStart(2, '0')}/08`,
        value: String(value),
        count: 20 + index,
      })),
      monthly: monthly.map((value, index) => ({
        label: ['set', 'out', 'nov', 'dez', 'jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago'][
          index
        ],
        value: String(value),
        count: 180 + index * 18,
      })),
      topProducts: Array.from({ length: 15 }, (_, index) => ({
        productId: `top-${index}`,
        code: `${['CAF', 'LEI', 'PAO', 'ACU', 'ARR'][index % 5]}-${String(index + 1).padStart(3, '0')}`,
        description: [
          'Café Especial',
          'Leite Integral',
          'Pão de Queijo',
          'Açúcar Cristal',
          'Arroz Premium',
        ][index % 5],
        quantity: String(482 - index * 21),
        total: String(15800 - index * 640),
        sales: 190 - index * 8,
      })),
      noSalesProducts: Array.from({ length: 8 }, (_, index) => ({
        id: `no-sale-${index}`,
        code: `SEM-${String(index + 1).padStart(3, '0')}`,
        description: ['Molho Artesanal', 'Kit Presente', 'Biscoito Integral', 'Chá Premium'][
          index % 4
        ],
      })),
      topCreditCustomers: Array.from({ length: 10 }, (_, index) => ({
        customerId: `credit-${index}`,
        name: [
          'Mercado Boa Mesa',
          'Comercial Lima',
          'Ana Martins',
          'Empório Central',
          'Carlos Nobre',
          'Padaria Tradição',
          'Beatriz Lima',
          'Supermercado Sol',
          'Daniela Souza',
          'Loja Conveniência',
        ][index],
        purchased: String(12800 - index * 780),
        openAmount: String(3200 - index * 170),
        purchases: 32 - index * 2,
      })),
    };
  }
  if (path.startsWith('/cash/operations'))
    return {
      totals: { sales: 3, gross: '384.70', fees: '5.55', net: '379.15' },
      records: [
        {
          id: 'sale-001',
          number: 'PDV-000184',
          soldAt: new Date(Date.now() - 42 * 60_000).toISOString(),
          status: 'completed',
          origin: 'pos',
          customer: 'Ana Martins',
          operator: 'Marina Costa',
          total: '219.80',
          feeAmount: '5.55',
          netAmount: '214.25',
          payments: [{ method: 'Cartão de crédito', amount: '219.80', installments: 3 }],
          fiscal: { type: 'NFC-e', status: 'authorized', number: '184' },
        },
        {
          id: 'sale-002',
          number: 'PDV-000183',
          soldAt: new Date(Date.now() - 96 * 60_000).toISOString(),
          status: 'completed',
          origin: 'pos',
          customer: 'Consumidor não identificado',
          operator: 'Marina Costa',
          total: '98.40',
          feeAmount: '0.00',
          netAmount: '98.40',
          payments: [{ method: 'PIX', amount: '98.40', installments: 1 }],
          fiscal: { type: 'NFC-e', status: 'authorized', number: '183' },
        },
        {
          id: 'sale-003',
          number: 'PDV-000182',
          soldAt: new Date(Date.now() - 155 * 60_000).toISOString(),
          status: 'completed',
          origin: 'food',
          customer: 'Mercado Boa Mesa',
          operator: 'Marina Costa',
          total: '66.50',
          feeAmount: '0.00',
          netAmount: '66.50',
          payments: [{ method: 'Dinheiro', amount: '66.50', installments: 1 }],
          fiscal: null,
        },
      ],
    };
  if (path.startsWith('/cash/tape'))
    return {
      totals: { entries: 5, inflows: '684.70', outflows: '80.00', balance: '604.70' },
      entries: [
        {
          id: 't1',
          occurredAt: new Date(Date.now() - 8 * 60 * 60_000).toISOString(),
          type: 'opening',
          description: 'Fundo de troco',
          amount: '300.00',
          direction: 'in',
          method: 'Dinheiro',
          register: 'CAIXA 01',
          operator: 'Marina Costa',
        },
        {
          id: 't2',
          occurredAt: new Date(Date.now() - 155 * 60_000).toISOString(),
          type: 'receipt',
          description: 'Venda PDV-000182',
          amount: '66.50',
          direction: 'in',
          method: 'Dinheiro',
          register: 'CAIXA 01',
          operator: 'Marina Costa',
        },
        {
          id: 't3',
          occurredAt: new Date(Date.now() - 96 * 60_000).toISOString(),
          type: 'receipt',
          description: 'Venda PDV-000183',
          amount: '98.40',
          direction: 'in',
          method: 'PIX',
          register: 'CAIXA 01',
          operator: 'Marina Costa',
        },
        {
          id: 't4',
          occurredAt: new Date(Date.now() - 42 * 60_000).toISOString(),
          type: 'receipt',
          description: 'Venda PDV-000184',
          amount: '219.80',
          direction: 'in',
          method: 'Cartão de crédito',
          register: 'CAIXA 01',
          operator: 'Marina Costa',
        },
        {
          id: 't5',
          occurredAt: new Date(Date.now() - 18 * 60_000).toISOString(),
          type: 'withdrawal',
          description: 'Sangria para cofre',
          amount: '80.00',
          direction: 'out',
          method: 'Dinheiro',
          register: 'CAIXA 01',
          operator: 'Marina Costa',
        },
      ],
    };
  if (path === '/cash/configuration')
    return {
      cardOperators: [
        {
          id: '018f4f12-2222-7222-8222-000000000701',
          code: 'REDE',
          name: 'Rede',
          taxId: '01027058000191',
          debitRate: '1.49',
          creditRate: '2.89',
          installmentRate: '0.35',
          settlementDays: 30,
          active: true,
        },
      ],
      paymentMethods: [
        {
          id: '018f4f12-2222-7222-8222-000000000301',
          code: 'DINHEIRO',
          name: 'Dinheiro',
          type: 'cash',
          fiscalCode: '01',
          cardOperatorId: null,
          maxInstallments: 1,
          createsReceivable: false,
          active: true,
        },
        {
          id: '018f4f12-2222-7222-8222-000000000302',
          code: 'PIX',
          name: 'PIX',
          type: 'pix',
          fiscalCode: '17',
          cardOperatorId: null,
          maxInstallments: 1,
          createsReceivable: false,
          active: true,
        },
        {
          id: '018f4f12-2222-7222-8222-000000000304',
          code: 'CREDITO',
          name: 'Cartão de crédito',
          type: 'credit_card',
          fiscalCode: '03',
          cardOperatorId: '018f4f12-2222-7222-8222-000000000701',
          maxInstallments: 12,
          createsReceivable: true,
          active: true,
        },
      ],
    };
  if (path.startsWith('/cash/card-operators') || path.startsWith('/cash/payment-methods'))
    return { ok: true };
  if (path === '/food/overview')
    return {
      tables: Array.from({ length: 12 }, (_, index) => ({
        id: `table-${index + 1}`,
        code: `M${String(index + 1).padStart(2, '0')}`,
        name: `Mesa ${index + 1}`,
        capacity: index % 3 === 0 ? 6 : 4,
        status: [0, 3, 7].includes(index) ? 'occupied' : 'free',
        publicToken: `00000000-0000-4000-8000-${String(index + 1).padStart(12, '0')}`,
      })),
      waiters: [
        { id: 'waiter-1', name: 'Carlos Lima' },
        { id: 'waiter-2', name: 'Bianca Alves' },
      ],
      customers: [],
      products: [
        {
          id: 'p1',
          code: 'CAF-001',
          description: 'Café Especial',
          printSector: 'Bar',
          price: '8.50',
        },
        {
          id: 'p3',
          code: 'PAO-001',
          description: 'Pão de Queijo',
          printSector: 'Cozinha',
          price: '12.50',
        },
        {
          id: 'p4',
          code: 'BRU-001',
          description: 'Bruschetta da Casa',
          printSector: 'Cozinha',
          price: '24.90',
        },
      ],
      paymentMethods: [
        { id: '018f4f12-2222-7222-8222-000000000301', name: 'Dinheiro', type: 'cash' },
        { id: '018f4f12-2222-7222-8222-000000000302', name: 'PIX', type: 'pix' },
      ],
      locations: [
        { id: '018f4f12-2222-7222-8222-000000000401', code: 'LOJA', name: 'Estoque da loja' },
      ],
      tabs: [
        {
          id: 'tab-1',
          tableId: 'table-1',
          number: 'CMD-001',
          channel: 'table',
          waiterId: 'waiter-1',
          guests: 3,
          openedAt: new Date().toISOString(),
          itemCount: 4,
          total: '87.30',
        },
        {
          id: 'tab-2',
          tableId: 'table-1',
          number: 'CMD-002',
          channel: 'table',
          waiterId: 'waiter-2',
          guests: 2,
          openedAt: new Date().toISOString(),
          itemCount: 2,
          total: '39.80',
        },
        {
          id: 'tab-3',
          tableId: 'table-4',
          number: 'CMD-003',
          channel: 'table',
          waiterId: 'waiter-1',
          guests: 4,
          openedAt: new Date().toISOString(),
          itemCount: 6,
          total: '142.60',
        },
        {
          id: 'tab-4',
          tableId: 'table-8',
          number: 'CMD-004',
          channel: 'table',
          waiterId: 'waiter-2',
          guests: 2,
          openedAt: new Date().toISOString(),
          itemCount: 3,
          total: '64.70',
        },
        {
          id: 'tab-counter',
          tableId: null,
          number: 'BAL-021',
          channel: 'counter',
          waiterId: 'waiter-1',
          guests: 1,
          openedAt: new Date().toISOString(),
          itemCount: 2,
          total: '31.40',
        },
        {
          id: 'tab-pickup',
          tableId: null,
          number: 'RET-014',
          channel: 'pickup',
          waiterId: 'waiter-2',
          guests: 1,
          openedAt: new Date().toISOString(),
          itemCount: 3,
          total: '58.90',
        },
        {
          id: 'tab-delivery',
          tableId: null,
          number: 'DEL-108',
          channel: 'delivery',
          waiterId: 'waiter-1',
          guests: 1,
          openedAt: new Date().toISOString(),
          itemCount: 4,
          total: '86.20',
        },
        {
          id: 'tab-kiosk',
          tableId: null,
          number: 'TOT-033',
          channel: 'kiosk',
          waiterId: null,
          guests: 1,
          openedAt: new Date().toISOString(),
          itemCount: 1,
          total: '24.90',
        },
        {
          id: 'tab-digital',
          tableId: null,
          number: 'DIG-041',
          channel: 'digital_menu',
          waiterId: null,
          guests: 2,
          openedAt: new Date().toISOString(),
          itemCount: 2,
          total: '49.80',
        },
      ],
    };
  if (path === '/food/tabs' && method !== 'GET') return { id: 'tab-channel-new' };
  if (path.startsWith('/food/tabs/') && path.endsWith('/items')) return { ok: true };
  if (path.startsWith('/food/tabs/') && path.endsWith('/close')) return { ok: true };
  if (path === '/delivery/overview')
    return {
      drivers: [
        {
          id: '018f4f12-2222-7222-8222-000000000701',
          name: 'Rafael Motta',
          phone: '(85) 99999-1001',
        },
        {
          id: '018f4f12-2222-7222-8222-000000000702',
          name: 'Júlia Rocha',
          phone: '(85) 99999-1002',
        },
      ],
      zones: [{ id: 'zone-1', name: 'Centro', calculationType: 'neighborhood', fee: '8.00' }],
      orders: [
        {
          id: '018f4f12-2222-7222-8222-000000000801',
          number: 'PED-1042',
          total: '76.40',
          customerName: 'Ana Martins',
          addresses: [
            {
              id: '018f4f12-2222-7222-8222-000000000901',
              label: 'Rua das Flores, 120 · Centro · Fortaleza/CE',
            },
          ],
        },
      ],
      deliveries: [
        {
          id: 'd1',
          status: 'new',
          orderNumber: 'PED-1037',
          customerName: 'Marcos Silva',
          customerPhone: '(85) 99999-0011',
          address: 'Rua A, 30 · Centro · Fortaleza/CE',
          driverId: null,
          driverName: null,
          fee: '8.00',
          distanceKm: '2.4',
          promisedAt: new Date(Date.now() + 30 * 60_000).toISOString(),
          createdAt: new Date().toISOString(),
        },
        {
          id: 'd2',
          status: 'preparing',
          orderNumber: 'PED-1038',
          customerName: 'Beatriz Lima',
          customerPhone: null,
          address: 'Av. Santos Dumont, 600 · Aldeota · Fortaleza/CE',
          driverId: null,
          driverName: null,
          fee: '12.00',
          distanceKm: '5.8',
          promisedAt: new Date(Date.now() + 45 * 60_000).toISOString(),
          createdAt: new Date().toISOString(),
        },
        {
          id: 'd3',
          status: 'ready',
          orderNumber: 'PED-1039',
          customerName: 'Carlos Nobre',
          customerPhone: null,
          address: 'Rua Silva Jatahy, 88 · Meireles · Fortaleza/CE',
          driverId: null,
          driverName: null,
          fee: '10.00',
          distanceKm: '4.1',
          promisedAt: new Date(Date.now() + 15 * 60_000).toISOString(),
          createdAt: new Date().toISOString(),
        },
        {
          id: 'd4',
          status: 'out_for_delivery',
          orderNumber: 'PED-1040',
          customerName: 'Daniela Souza',
          customerPhone: null,
          address: 'Rua B, 220 · Benfica · Fortaleza/CE',
          driverId: '018f4f12-2222-7222-8222-000000000701',
          driverName: 'Rafael Motta',
          fee: '14.00',
          distanceKm: '7.2',
          promisedAt: new Date(Date.now() + 10 * 60_000).toISOString(),
          createdAt: new Date().toISOString(),
        },
      ],
    };
  if (path === '/food/tabs/tab-1/summary')
    return {
      tab: { number: 'CMD-001', openedAt: new Date().toISOString(), guests: 3 },
      items: [
        {
          id: 'i1',
          description: 'Bruschetta da Casa',
          quantity: '2',
          unitPrice: '24.90',
          total: '49.80',
          notes: null,
        },
        {
          id: 'i2',
          description: 'Café Especial',
          quantity: '3',
          unitPrice: '8.50',
          total: '25.50',
          notes: 'Um sem açúcar',
        },
        {
          id: 'i3',
          description: 'Pão de Queijo',
          quantity: '1',
          unitPrice: '12.00',
          total: '12.00',
          notes: null,
        },
      ],
      total: '87.30',
    };
  if (path.startsWith('/food/tabs/') && path.endsWith('/summary'))
    return {
      tab: { number: 'ATD-DEMO', openedAt: new Date().toISOString(), guests: 1 },
      items: [
        {
          id: 'channel-item-1',
          productId: 'p4',
          description: 'Bruschetta da Casa',
          quantity: '1',
          unitPrice: '24.90',
          total: '24.90',
          notes: null,
        },
        {
          id: 'channel-item-2',
          productId: 'p1',
          description: 'Café Especial',
          quantity: '1',
          unitPrice: '8.50',
          total: '8.50',
          notes: null,
        },
      ],
      total: '33.40',
    };
  if (path.includes('/checkout'))
    return {
      orderId: '018f4f12-2222-7222-8222-000000000501',
      orderNumber: 'FOOD-DEMO',
      saleId: '018f4f12-2222-7222-8222-000000000502',
      saleNumber: 'VEN-DEMO',
      total: '87.30',
      itemCount: 3,
      paymentCount: 1,
      soldAt: new Date().toISOString(),
      issuer: {
        tradeName: 'ERP Híbrido Mercado',
        legalName: 'ERP Híbrido Comércio e Tecnologia Ltda.',
        taxId: '01027058000191',
      },
    };
  if (path.startsWith('/fiscal/nfce/'))
    return {
      status: 'authorized',
      accessKey: '23260800000000000191650010000000011000000010',
      protocol: '323260000000001',
      series: '1',
      number: '1',
      issuedAt: new Date().toISOString(),
      qrCodeUrl: 'https://www.nfe.fazenda.gov.br/portal/principal.aspx',
      total: '87.30',
    };
  throw new Error('Demonstração sem resposta para este recurso');
}

function demoOrder(id: string, number: string, status: string, customer: string, total: string) {
  return {
    id,
    number,
    status,
    origin: 'sales_quote',
    customer: { id: `customer-${id}`, name: customer },
    seller: { id: 'seller-1', name: 'Marina Costa' },
    paymentMethod: { id: 'method-1', name: 'PIX' },
    subtotal: total,
    discount: '0',
    surcharge: '0',
    freight: '0',
    total,
    notes: null,
    items: [],
    createdAt: new Date().toISOString(),
  };
}
