import { useEffect, useState } from 'react';
import type { RoleSummary } from '@erp/contracts';
import { apiRequest } from '../api';
import { PageHeader } from './BranchesPanel';

interface Permission { id: string; code: string; resource: string; action: string }
export function RolesPanel({ canManage }: { canManage: boolean }) {
  const [roles, setRoles] = useState<RoleSummary[]>([]); const [permissions, setPermissions] = useState<Permission[]>([]); const [selected, setSelected] = useState<RoleSummary | null>(null); const [creating, setCreating] = useState(false); const [error, setError] = useState('');
  async function load(): Promise<void> { try { const [nextRoles, nextPermissions] = await Promise.all([apiRequest<RoleSummary[]>('/admin/roles'), apiRequest<Permission[]>('/admin/permissions')]); setRoles(nextRoles); setPermissions(nextPermissions); setSelected((current) => current ? nextRoles.find(({ id }) => id === current.id) ?? null : null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao carregar'); } }
  useEffect(() => { void load(); }, []);
  async function create(event: React.FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const data = new FormData(event.currentTarget); try { await apiRequest('/admin/roles', { method: 'POST', body: JSON.stringify({ code: data.get('code'), name: data.get('name') }) }); setCreating(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao salvar'); } }
  async function toggle(permissionId: string): Promise<void> { if (!selected || !canManage) return; const permissionIds = selected.permissionIds.includes(permissionId) ? selected.permissionIds.filter((id) => id !== permissionId) : [...selected.permissionIds, permissionId]; try { await apiRequest(`/admin/roles/${selected.id}/permissions`, { method: 'PUT', body: JSON.stringify({ permissionIds }) }); setSelected({ ...selected, permissionIds }); setRoles((current) => current.map((role) => role.id === selected.id ? { ...role, permissionIds } : role)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao atualizar'); } }
  return <section><PageHeader title="Perfis e permissões" description="Defina exatamente o que cada equipe pode acessar." action={canManage ? () => setCreating(true) : undefined} />{error && <div className="error">{error}</div>}{creating && <form className="inline-form compact" onSubmit={(event) => void create(event)}><label>Código<input name="code" placeholder="financeiro.operador" required /></label><label>Nome<input name="name" required /></label><div className="form-actions"><button type="button" className="quiet" onClick={() => setCreating(false)}>Cancelar</button><button className="primary">Criar perfil</button></div></form>}<div className="split-panel"><div className="role-list">{roles.map((role) => <button key={role.id} className={selected?.id === role.id ? 'selected' : ''} onClick={() => setSelected(role)}><strong>{role.name}</strong><span>{role.permissionIds.length} permissões</span></button>)}</div><div className="permission-list">{selected ? <><h2>{selected.name}</h2>{permissions.map((permission) => <label key={permission.id} className="check-row"><input type="checkbox" checked={selected.permissionIds.includes(permission.id)} disabled={!canManage} onChange={() => void toggle(permission.id)} /><span><strong>{permission.resource}</strong><small>{permission.action}</small></span></label>)}</> : <div className="empty-row">Selecione um perfil.</div>}</div></div></section>;
}
