import { useEffect, useState } from 'react';
import type { AdminUserSummary, BranchSummary, RoleSummary } from '@erp/contracts';
import { apiRequest } from '../api';
import { PageHeader } from './BranchesPanel';

export function UsersPanel({ canManage }: { canManage: boolean }) {
  const [users, setUsers] = useState<AdminUserSummary[]>([]); const [branches, setBranches] = useState<BranchSummary[]>([]); const [roles, setRoles] = useState<RoleSummary[]>([]); const [inviting, setInviting] = useState(false); const [error, setError] = useState('');
  async function load(): Promise<void> { try { const [nextUsers, nextBranches, nextRoles] = await Promise.all([apiRequest<AdminUserSummary[]>('/admin/users'), apiRequest<BranchSummary[]>('/admin/branches'), apiRequest<RoleSummary[]>('/admin/roles')]); setUsers(nextUsers); setBranches(nextBranches); setRoles(nextRoles); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao carregar'); } }
  useEffect(() => { void load(); }, []);
  async function invite(event: React.FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const data = new FormData(event.currentTarget); try { await apiRequest('/admin/users/invitations', { method: 'POST', body: JSON.stringify({ email: data.get('email'), displayName: data.get('displayName'), branchIds: data.getAll('branchIds'), roleIds: data.getAll('roleIds') }) }); setInviting(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao convidar'); } }
  async function toggleStatus(user: AdminUserSummary): Promise<void> { const status = user.status === 'active' ? 'inactive' : 'active'; try { await apiRequest(`/admin/users/${user.id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao atualizar'); } }
  return <section><PageHeader title="Usuários" description="Pessoas autorizadas a operar nesta empresa." action={canManage ? () => setInviting(true) : undefined} />{error && <div className="error">{error}</div>}{inviting && <form className="inline-form" onSubmit={(event) => void invite(event)}><label>Nome<input name="displayName" required /></label><label>E-mail<input name="email" type="email" required /></label><fieldset><legend>Filiais</legend>{branches.map((branch) => <label className="option" key={branch.id}><input type="checkbox" name="branchIds" value={branch.id} />{branch.code}</label>)}</fieldset><fieldset><legend>Perfis</legend>{roles.map((role) => <label className="option" key={role.id}><input type="checkbox" name="roleIds" value={role.id} />{role.name}</label>)}</fieldset><div className="form-actions"><button type="button" className="quiet" onClick={() => setInviting(false)}>Cancelar</button><button className="primary">Enviar convite</button></div></form>}<div className="table-card"><table><thead><tr><th>Usuário</th><th>E-mail</th><th>Acessos</th><th>Status</th><th /></tr></thead><tbody>{users.map((item) => <tr key={item.id}><td><strong>{item.user?.displayName ?? 'Usuário'}</strong></td><td>{item.user?.email}</td><td>{item.branchIds.length} filiais · {item.roleIds.length} perfis</td><td><span className={`badge ${item.status}`}>{item.status === 'active' ? 'Ativo' : 'Inativo'}</span></td><td>{canManage && <button className="link" onClick={() => void toggleStatus(item)}>{item.status === 'active' ? 'Inativar' : 'Ativar'}</button>}</td></tr>)}</tbody></table>{users.length === 0 && <div className="empty-row">Nenhum usuário encontrado.</div>}</div></section>;
}
